### ISSUE TITLE
Diseño del Proyecto

### ISSUE THREAD

**Issue by mcm0151** [fabdelgado/GESPRO_GESTIONTAREAS#11]
Tarea para diseñar el proyecto

**Comment by mcm0151** [comment]
Empezamos a diseñar el proyecto.

**Comment by fabdelgado** [comment]
Adjunto la primera versión del documento de diseño
[diseñov1.pdf](https://github.com/fabdelgado/GESPRO_GESTIONTAREAS/files/3843602/disenov1.pdf)

**Comment by fabdelgado** [comment]
Se entrega el documento final.
[diseño_final.pdf](https://github.com/fabdelgado/GESPRO_GESTIONTAREAS/files/3843603/diseno_final.pdf)

**Comment by mcm0151** [comment]
Se da por finalizado el diseño del proyecto.
