### ISSUE TITLE
Reunir el equipo

### ISSUE THREAD

**Issue by mcm0151** [fabdelgado/GESPRO_GESTIONTAREAS#12]
Esta tarea pretende establecer los criterios para reunir un grupo de personas.

**Comment by fabdelgado** [comment]
Hemos reunido al equipo:
Silene Oliveira (Tokio)
Sergio Marquina (El Profesor)
Agustín Ramos (Moscú)
Andrés de Fonollosa (Berlín)
Ágata Jiménez (Naerobi)
Aníbal Cortés (Río)
Ricardo Ramos (Denver)
Mónica Gaztambide (Estocolmo)

**Comment by fabdelgado** [comment]
Se cierra la tarea, ya que se cuenta con el equipo.
